// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NvAssist
{
    internal sealed partial class Vsix
    {
        public const string Id = "NvAssist.4b5741a1-bc59-4ad5-a7b8-1d7fb720bb6e";
        public const string Name = "NvAssist";
        public const string Description = @"Productivity tool.";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "NVIDIA";
        public const string Tags = "";
    }
}
